services:
  api:
    build:
      context: .
      dockerfile: apps/api/Dockerfile
    ports:
      - "3000:3000" # Expose the API's port

  web:
    build:
      context: .
      dockerfile: apps/web/Dockerfile
    ports:
      - "5137:5137"
